---
title: "Codebook"
output:
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Getting and Cleaning Data - Course Project

## Changes to the data

The following tasks were done on the original data set to create the clean data set:
* merged into one data set by combining training and test tests
* shortened to only include the measurements of the mean and standard deviation of each measurement
* renamed each activity in the data set using descriptive names
* dataset was relabelled with descriptive variable names
* took the average of each variable for each activity and each subject - the values created the independent tiny dataset

## Data Descriptions
###Identififiers
The second last column identifies the activity by name
The last column identifies the ID of the subject 


###Measurements
As mentioned above,the variables remaining are just the calculated means and standard deviations of all measurements in the data set:

Show in New WindowClear OutputExpand/Collapse Output
* tBodyAcc-mean()-X               
* tBodyAcc-mean()-Y              
* tBodyAcc-mean()-Z               
* tBodyAcc-std()-X               
* tBodyAcc-std()-Y                
* tBodyAcc-std()-Z               
* tGravityAcc-mean()-X            
* tGravityAcc-mean()-Y           
* tGravityAcc-mean()-Z            
* tGravityAcc-std()-X            
* tGravityAcc-std()-Y             
* tGravityAcc-std()-Z            
* tBodyAccJerk-mean()-X           
* tBodyAccJerk-mean()-Y          
* tBodyAccJerk-mean()-Z           
* tBodyAccJerk-std()-X           
* tBodyAccJerk-std()-Y            
* tBodyAccJerk-std()-Z           
* tBodyGyro-mean()-X             
* tBodyGyro-mean()-Y             
* tBodyGyro-mean()-Z              
* tBodyGyro-std()-X              
* tBodyGyro-std()-Y               
* tBodyGyro-std()-Z              
* tBodyGyroJerk-mean()-X          
* tBodyGyroJerk-mean()-Y         
* tBodyGyroJerk-mean()-Z          
* tBodyGyroJerk-std()-X          
* tBodyGyroJerk-std()-Y           
* tBodyGyroJerk-std()-Z          
* tBodyAccMag-mean()              
* tBodyAccMag-std()              
* tGravityAccMag-mean()          
* tGravityAccMag-std()           
* tBodyAccJerkMag-mean()          
* tBodyAccJerkMag-std()         
* tBodyGyroMag-mean()             
* tBodyGyroMag-std()             
* tBodyGyroJerkMag-mean()         
* tBodyGyroJerkMag-std()         
* fBodyAcc-mean()-X               
* fBodyAcc-mean()-Y              
* fBodyAcc-mean()-Z               
* fBodyAcc-std()-X               
* fBodyAcc-std()-Y                
* fBodyAcc-std()-Z               
* fBodyAcc-meanFreq()-X          
* fBodyAcc-meanFreq()-Y         
* fBodyAcc-meanFreq()-Z          
* fBodyAccJerk-mean()-X         
* fBodyAccJerk-mean()-Y          
* fBodyAccJerk-mean()-Z        
* fBodyAccJerk-std()-X        
* fBodyAccJerk-std()-Y          
* fBodyAccJerk-std()-Z           
* fBodyAccJerk-meanFreq()-X     
* fBodyAccJerk-meanFreq()-Y       
* fBodyAccJerk-meanFreq()-Z      
* fBodyGyro-mean()-X              
* fBodyGyro-mean()-Y             
* fBodyGyro-mean()-Z              
* fBodyGyro-std()-X              
* fBodyGyro-std()-Y               
* fBodyGyro-std()-Z              
* fBodyGyro-meanFreq()-X          
* fBodyGyro-meanFreq()-Y         
* fBodyGyro-meanFreq()-Z          
* fBodyAccMag-mean()             
* fBodyAccMag-std()            
* fBodyAccMag-meanFreq()       
* fBodyBodyAccJerkMag-mean()   
* fBodyBodyAccJerkMag-std()  
* fBodyBodyAccJerkMag-meanFreq()
* fBodyBodyGyroMag-mean()        
* fBodyBodyGyroMag-std()         
* fBodyBodyGyroMag-meanFreq()    
* fBodyBodyGyroJerkMag-mean()     
* fBodyBodyGyroJerkMag-std()    
* fBodyBodyGyroJerkMag-meanFreq() 
* Activity                       
* Subject 

## Tiny dataset

The tiny dataset contains the same variable names shown. 


